# Generated by Django 2.0.6 on 2018-07-11 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=200)),
                ('description', models.CharField(default='n/a', max_length=1000)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 21, 42, 44, 934889, tzinfo=utc), verbose_name='date published')),
                ('words', models.IntegerField(default=0)),
            ],
        ),
    ]
