# Generated by Django 2.0.6 on 2018-07-11 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=200)),
                ('description', models.CharField(default='n/a', max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 22, 2, 23, 162436, tzinfo=utc), verbose_name='date published')),
                ('path', models.CharField(default='n/a', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=200)),
                ('description', models.CharField(default='n/a', max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 22, 2, 23, 129316, tzinfo=utc), verbose_name='date published')),
                ('word_count', models.IntegerField(default=0)),
                ('content', models.TextField(default='n/a')),
            ],
        ),
        migrations.DeleteModel(
            name='ProduceObject',
        ),
    ]
