# Generated by Django 2.0.6 on 2018-07-11 22:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_auto_20180711_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualobject',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 22, 32, 48, 293193, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='writtenobject',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 22, 32, 48, 280067, tzinfo=utc), verbose_name='date published'),
        ),
    ]
