# Generated by Django 2.0.6 on 2018-07-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0004_auto_20180712_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualobject',
            name='content',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
