# Generated by Django 2.0.6 on 2018-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusobject',
            name='status_title',
            field=models.CharField(default='update', max_length=200),
        ),
    ]
