# Generated by Django 2.0.6 on 2018-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_statusobject_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusobject',
            name='status_text',
            field=models.CharField(default='no text', max_length=1000),
        ),
    ]
