# Generated by Django 2.0.6 on 2018-07-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20180706_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusobject',
            name='status_text',
            field=models.TextField(default='no text', max_length=5000),
        ),
    ]
