# Generated by Django 2.0.6 on 2018-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_auto_20180712_1450'),
        ('status', '0005_auto_20180712_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusobject',
            name='cited_works',
            field=models.ManyToManyField(to='library.LibraryObject'),
        ),
    ]
