# Generated by Django 2.0.6 on 2018-07-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_statusobject_cited_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusobject',
            name='cited_works',
            field=models.ManyToManyField(blank=True, to='library.LibraryObject'),
        ),
    ]
