# Generated by Django 2.0.6 on 2018-07-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20180714_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusobject',
            name='status_text',
            field=models.TextField(default='There is no text.', max_length=5000),
        ),
    ]
