# Generated by Django 2.0.6 on 2018-07-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_auto_20180716_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusobject',
            name='description',
            field=models.CharField(default='no description', max_length=500),
        ),
    ]
