# Generated by Django 3.2.6 on 2021-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_statusobject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusobject',
            name='status_type',
            field=models.CharField(choices=[('T', 'Technical Status'), ('L', 'Literature Status'), ('N', 'Neutral Status')], default='N', max_length=1),
        ),
    ]
