# Generated by Django 3.2.6 on 2021-09-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_statusobject_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusobject',
            name='status_text',
            field=models.TextField(default='There is no text.', max_length=10000),
        ),
    ]
